#!/bin/bash
ps ax | grep dropbear > /tmp/PID.txt
cat /var/log/auth.log |  grep -i "Password auth succeeded" | awk '{print $10,$5}' | sed s/.$//| column -t | sed "s/'//g" > /tmp/connet.txt
perl -pi -e 's/dropbear/PID/g' /tmp/connect.txt
cat /tmp/PID.txt | while read line;do
set -- $line
cat /tmp/connect.txt | grep $1 > /tmp/dead
cat /tmp/dead
done
